[package]
name = "gtirb-rs"
version = "0.1.0"
authors = ["Kevin Warrick <kevinjwarrick@gmail.com>"]
edition = "2018"

[dependencies]
generational-arena = "0.2.8"
uuid = { version = "0.8.1", features = ["v4"] }
